### ISSUE TITLE
license subcommand returns error

### ISSUE THREAD

**Issue by excelero-andreas** [Excelero/nvmesh-shell#1]
nvmesh # license
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 2396, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 2591, in onecmd
    stop = func(statement)
TypeError: do_license() takes exactly 2 arguments (1 given)
EXCEPTION of type 'TypeError' occurred with message: 'do_license() takes exactly 2 arguments (1 given)'

**Comment by excelero-andreas** [comment]
fixed with version v0.1.4
