### ISSUE TITLE
Cannot limit `runcmd` to execute against a specific list of servers

### ISSUE THREAD

**Issue by excelero-joe** [Excelero/nvmesh-shell#2]
Trying to run a command using `runcmd` against a subset of systems in the cluster by passing a list (tried comma and space separated) to the `-s` parameter, but it gives an error.

```
nvmesh # runcmd cluster -Pp -c uptime -s "uslab-21 uslab-22"
Couldn't execute command uptime on uslab-21 uslab-22 !
None
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 2468, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 2663, in onecmd
    stop = func(statement)
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 496, in cmd_wrapper
    return func(instance, args)
  File "/usr/lib/python2.7/site-packages/nvmesh_shell.py", line 1329, in do_runcmd
    self.poutput(run_command(args.command, args.scope, args.prefix, args.parallel, args.servers))
  File "/usr/lib/python2.7/site-packages/nvmesh_shell.py", line 802, in run_command
    if command_return[1][0] != 0:
TypeError: 'NoneType' object has no attribute '__getitem__'
EXCEPTION of type 'TypeError' occurred with message: ''NoneType' object has no attribute '__getitem__''
To enable full traceback, run the following command:  'set debug true'
nvmesh # runcmd cluster -Pp -c uptime -s "uslab-21,uslab-22"
Couldn't execute command uptime on uslab-21,uslab-22 !
None
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 2468, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 2663, in onecmd
    stop = func(statement)
  File "/usr/lib64/python2.7/site-packages/cmd2.py", line 496, in cmd_wrapper
    return func(instance, args)
  File "/usr/lib/python2.7/site-packages/nvmesh_shell.py", line 1329, in do_runcmd
    self.poutput(run_command(args.command, args.scope, args.prefix, args.parallel, args.servers))
  File "/usr/lib/python2.7/site-packages/nvmesh_shell.py", line 802, in run_command
    if command_return[1][0] != 0:
TypeError: 'NoneType' object has no attribute '__getitem__'
EXCEPTION of type 'TypeError' occurred with message: ''NoneType' object has no attribute '__getitem__''
To enable full traceback, run the following command:  'set debug true'
```

**Comment by excelero-andreas** [comment]
Only space separated lists are accepeted. Quotes are not required.
Run the command line: `runcmd cluster -Pp -c uptime -s uslab-21 uslab-22`
This will work.
